apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: 80
      port: 80
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: my-nainx-app