apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-pv
spec:
  storageClassName: "my-local-storage"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/my-storage
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-pvc
spec:
  storageClassName: "my-local-storage" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi