apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.votingApp.appName }}
  labels:
    name: voting-app-deploy
    app: demo-voting-app  
spec:
  replicas: {{ .Values.votingApp.replica }}
  selector:
    matchLabels:
      app: voting-pod
  template:   # for pod definition
    metadata:
      name: voting-app-pod
      labels:
        app: voting-pod
    spec:
      containers:
      - name: voting
        image: {{ .Values.votingApp.image }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: voting-nodeport
spec:
  type: NodePort
  selector:
    app: voting-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
