apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.worker.appName }}
spec:
  replicas: {{ .Values.worker.replica }}
  selector:
    matchLabels:
      app: worker
  template:   # for pod definition
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.worker.image }}

