apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: nginx-1
    tier: frontend
    env: production
spec:
  containers:
    - name: nginx-1
      image: nginx 
      ports:
        - containerPort: 80